# Generated by Django 4.0.6 on 2023-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(related_name='subtask', to='Join.subtask'),
        ),
    ]
