# Generated by Django 4.0.6 on 2023-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0002_remove_task_subtask_task_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks', to='Join.subtask'),
        ),
    ]
