# Generated by Django 4.0.6 on 2023-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0003_remove_task_subtask_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.CharField(choices=[('To_Do', 'To Do'), ('In_Progress', 'In Progress'), ('Awaiting_Feedback', 'Awaiting Feedback'), ('Done', 'Done')], default='Todo', max_length=17),
        ),
    ]
