# Generated by Django 4.0.6 on 2023-11-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0004_category_task_due_date_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
